name: my_personal_avaliator
description: My Personal Avaliator App.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flushbar: ^1.10.4
  carousel_slider: ^2.1.0
  flutter_secure_storage: ^3.3.3
  equatable: ^1.2.0
  rxdart: ^0.24.1
  http: ^0.12.1
  flutter_bloc: ^5.0.1
  meta: ^1.1.8
  cupertino_icons: ^0.1.2
  flutter_markdown: ^0.4.2
  freezed_annotation: ^0.11.0
  dartz: ^0.9.1
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  injectable: ^0.4.0+1
  get_it: ^4.0.2
dev_dependencies:
  build_runner:
  lint: ^1.2.0
  freezed: ^0.11.2
  injectable_generator: ^0.4.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
